name: Update server side generated pages

on:
  push:
    branches:
      - stable

defaults:
  run:
    shell: bash -l {0}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-ssg:
    name: Update server side generated pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure git to use https
        run: git config --global hub.protocol https

      - name: Checkout the branch
        run: |
          git checkout stable
          git checkout -B stable-ssg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Install solara
        run: |
          pip install -e ".[documentation]" playwright==1.39.0
          (cd packages/solara-enterprise && pip install ".[all]")

      - name: Install Playwright
        run: |
          playwright install chromium

      - name: Generate pages
        run: solara ssg solara.website.pages

      - name: Commit reference images
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

          git add -f solara/website/build
          git commit -m "Update SSG pages"
          git push origin stable-ssg -f
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
